@startuml
object client1 {
    id = 1
    username = "john_doe"
    email = "john@example.com"
}

object cart1 {
    id = 1
    total = 150.00
    bought = false
}

object wishlist1 {
    id = 1
}

object product1 {
    id = 1
    productName = "Handmade Bag"
    price = 100.00
    stock = 10
}

object cartItem1 {
    id = 1
    quantity = 2
}

object wishItem1 {
    id = 1
}

object category1 {
    id = 1
    categoryName = "Bags"
}

client1 -- cart1
client1 -- wishlist1
cart1 -- cartItem1
wishlist1 -- wishItem1
cartItem1 -- product1
wishItem1 -- product1
product1 -- category1

@enduml